bookstore/urls.py
from django.urls import path, include
from bookstore import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.book_list, name='books'),
    path('books/<int:bid>/', views.related_transaction, name='related_transaction'),
    path('books/<int:bid>/add/', views.add_book, name='addbook'),
    path('books/<int:bid>/sell/', views.sell_book, name='sellbook'),
    path('books/<int:bid>/edit/', views.edit_book, name='editbook'),
    path('newbook/', views.new_book, name='newbook'),
    path('transactions/', views.transactions, name='transactions'),
    path('transactions/payment/', views.payment, name='payment'),
    path('publishers/', views.publishers, name='publishers'),
    path('publishers/<int:pid>/', views.pub_books, name='pub_books'),
    path('publishers/<int:pid>/update/', views.pub_update, name='pub_update'),
    path('authors/', views.authors, name='authors'),
    path('authors/<int:aid>/', views.author_books, name='author_books'),
    path('authors/<int:aid>/update/', views.author_update, name='author_update'),
    path('categories/', views.categories, name='categories'),
    path('categories/<int:cid>/', views.cat_books, name='cat_books'),
    path('categories/<int:cid>/update/', views.cat_update, name='cat_update'),
    # path('login/', views.login, name='login'),
    # path('logout/', views.logout, name='logout'),
    # path('user/<int:uid>/pwd_reset', views.pwd_reset, name='pwd_reset'),
    path('user/<int:uid>/profile/', views.profile, name='profile'),
    path('user/<int:uid>/profile/update/', views.profile_update, name='profile_update'),
]

bookstore_management_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('bookstore/', include('bookstore.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/bookstore/')),
    # static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
]

bookstore/models.py
from django.core import validators as vl
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
import datetime


class Admin(models.Model):
    """
    管理员信息模式，包括 id、用户名、密码、是否为超级管理员、姓名、性别、年龄、地址、电话号码
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=30, verbose_name='姓名')
    gender = models.CharField(max_length=1, verbose_name='性别', help_text='请输入“男”或者“女”', validators=
                              [vl.RegexValidator(regex="^['男'|'女']$", message='请确保性别格式正确！')])
    age = models.PositiveIntegerField(verbose_name='年龄',
                                      validators=[vl.MaxValueValidator(99), vl.MinValueValidator(1)], default=18)
    address = models.CharField(max_length=50, verbose_name='住址')
    # phone = models.CharField(max_length=11, verbose_name='联系方式（手机）', help_text='请输入中国大陆11位手机号', validators=
    #                         [vl.RegexValidator(regex='^1(3|5|7|8|9)\d{9}$', message='请确保手机号格式正确！')])

    class Meta:
        verbose_name = '管理员信息'
        verbose_name_plural = '管理员信息'

    def __str__(self):
        return self.user.get_username()


class Phone(models.Model):
    admin = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='管理员姓名')
    number = models.CharField(max_length=11, verbose_name='联系方式（手机）', help_text='请输入中国大陆11位手机号', validators=
                              [vl.RegexValidator(regex='^1(3|5|7|8|9)\d{9}$', message='请确保手机号格式正确！')])

    class Meta:
        verbose_name = '联系方式'
        verbose_name_plural = '联系方式'

    def __str__(self):
        return self.number


class Publisher(models.Model):
    name = models.CharField(max_length=30, verbose_name='出版社')

    class Meta:
        verbose_name = '出版社'
        verbose_name_plural = '出版社'
        ordering = ['name', ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('pub_books', args=[str(self.id)])


class Category(models.Model):
    name = models.CharField(max_length=10, verbose_name='类别')

    class Meta:
        verbose_name = '类别'
        verbose_name_plural = '类别'
        ordering = ['name', ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('cat_books', args=[str(self.id)])


class Author(models.Model):
    name = models.CharField(max_length=30, verbose_name='作者姓名')

    class Meta:
        verbose_name = '作者'
        verbose_name_plural = '作者'
        ordering = ['name', ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('author_books', args=[str(self.id)])


class Book(models.Model):
    """
    书籍信息模式，包括 ISBN号、书名、出版社、价格、库存
    """
    ISBN = models.CharField(max_length=13, verbose_name='ISBN号', help_text='请输入纯数字ISBN（不带横杠）', validators=
                            [vl.RegexValidator(regex='^\d{13}$', message='请确保ISBN格式正确！')])
    name = models.CharField(max_length=50, verbose_name='书名')
    language = models.CharField(max_length=10, verbose_name='语言', default='汉语')
    author = models.ManyToManyField(Author, verbose_name='作者')
    publisher = models.ForeignKey(Publisher, on_delete=models.DO_NOTHING, verbose_name='出版社')
    price = models.DecimalField(max_digits=5, decimal_places=2, verbose_name='售价', validators=
                                [vl.MaxValueValidator(999.99, message='最高999.99元'),
                                 vl.MinValueValidator(0.01, message='最低0.01元')])
    inventory = models.IntegerField(verbose_name='当前库存', validators=[vl.MinValueValidator(0)], default=0)
    category = models.ManyToManyField(Category, verbose_name='类别')
    summary = models.CharField(max_length=100, verbose_name='简介', default='懒狗管理员没有留下任何摘要，是不是可以爬了？')

    class Meta:
        verbose_name = '图书信息'
        verbose_name_plural = '图书信息'
        ordering = ['name', 'publisher', ]

    def __str__(self):
        return '《' + self.name + '》，' + self.get_author() + '，' + self.ISBN + '，' + self.publisher.name

    def get_absolute_url(self):
        return reverse('related_transaction', args=[str(self.id)])

    def get_author(self):
        return '，'.join([a.name for a in self.author.order_by('name')])

    def get_category(self):
        return '，'.join([c.name for c in self.category.order_by('name')])


class Transaction(models.Model):
    """
    交易记录模式，包括 买入卖出、商品 ISBN号、交易价格、交易数量、交易时间、付款状态
    """
    in_out = models.CharField(max_length=2, verbose_name='进货/出货', help_text='请输入“进货”或者“出货”', validators=
                              [vl.RegexValidator(regex=(r'^(?:进货|出货)$'), message='请确保输入“进货”或者“出货”之一！')])
    book = models.ForeignKey(Book, on_delete=models.DO_NOTHING, verbose_name='商品')
    ruler = models.ForeignKey(Admin, on_delete=models.DO_NOTHING, verbose_name='执行交易的管理员')
    cost = models.DecimalField(max_digits=5, decimal_places=2, verbose_name='成交金额')
    amount = models.PositiveIntegerField(verbose_name='成交数量',
                                         validators=[vl.MinValueValidator(1), vl.MaxValueValidator(9999)])
    time = models.DateTimeField(auto_now_add=True, verbose_name='成交时间')
    paid = models.CharField(max_length=3, verbose_name='未付款/已付款/已退货', help_text='请输入“未付款“、”已付款“、”已退货“之一',
                            validators=[vl.RegexValidator(regex=(r'^(?:未付款|已付款|已退货)$'),
                                                          message='请确保输入“未付款“、”已付款“、”已退货“之一！')])

    class Meta:
        verbose_name = '交易记录'
        verbose_name_plural = '交易记录'
        ordering = ['-time']

    def __str__(self):
        rt = ''
        rt += 'Book name: ' + self.book.name
        rt += 'Author' + self.book.get_author()
        rt += '\nISBN: ' + self.book.ISBN
        rt += '\nDate: ' + str(self.time)
        rt += '\n' + self.paid
        return rt

    def recent_deal(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.time <= now

bookstore/forms.py
from django import forms
from django.core import validators as vl
from django.core.exceptions import ValidationError


class ProfileForm(forms.Form):
    '''
    修改管理员个人信
    '''
    sex = (('男', '男'), ('男', '女'))
    name = forms.CharField(label='姓名', max_length=30)
    age = forms.CharField(label='年龄', max_length=2)
    gender = forms.CharField(label='性别', widget=forms.widgets.Select(choices=sex))
    address = forms.CharField(label='住址', max_length=50)


class NewBookForm(forms.Form):
    '''
    新书上架
    '''
    ISBN = forms.CharField(label='ISBN', max_length=13)
    name = forms.CharField(label='书名', max_length=50)
    author = forms.CharField(label='作者', max_length=30)
    language = forms.CharField(label='作者', max_length=10)
    publisher = forms.CharField(label='出版社', max_length=30)
    category = forms.CharField(label='类型', max_length=10)
    cost = forms.DecimalField(label='进价', max_value=999.99, min_value=0.01, max_digits=5, decimal_places=2)
    price = forms.DecimalField(label='零售价', max_value=999.99, min_value=0.01, max_digits=5, decimal_places=2)
    amount = forms.IntegerField(label='数量', min_value=1)
    summary = forms.CharField(label='简介', max_length=100)


class SellForm(forms.Form):
    '''
    图书销售
    '''
    amount = forms.IntegerField(label='数量', min_value=1)


class AddForm(forms.Form):
    '''
    已有图书补充库存
    '''
    amount = forms.IntegerField(label='数量', min_value=1)
    cost = forms.DecimalField(label='进价', max_value=999.99, min_value=0.01, max_digits=5, decimal_places=2)


class SearchForm(forms.Form):
    '''
    按一定要求检索库存图书
    '''
    ISBN = forms.CharField(label='ISBN', max_length=13, required=False)
    name = forms.CharField(label='书名', max_length=50, required=False)
    author = forms.CharField(label='作者', max_length=30, required=False)
    language = forms.CharField(label='作者', max_length=10, required=False)
    publisher = forms.CharField(label='出版社', max_length=30, required=False)
    category = forms.CharField(label='类型', max_length=10, required=False)


class TimeSpanForm(forms.Form):
    '''
    按时间范围检索交易记录
    '''
    states = (('in', '进货'), ('out', '出货'))
    start_time = forms.DateTimeField(label='起始时间')
    end_time = forms.DateTimeField(label='结束时间')
    stat = forms.CharField(label='进货/出货', widget=forms.widgets.Select(choices=states))


class EditBookForm(forms.Form):
    '''
    编辑图书信息
    '''
    name = forms.CharField(label='书名', max_length=50)
    author = forms.CharField(label='作者', max_length=30)
    publisher = forms.CharField(label='出版社', max_length=30)
    language = forms.CharField(label='作者', max_length=10)
    price = forms.DecimalField(label='零售价', max_value=999.99, min_value=0.01, max_digits=5, decimal_places=2)
    category = forms.CharField(label='类型', max_length=10)
    summary = forms.CharField(label='简介', max_length=100)


class PayForm(forms.Form):
    '''
    为未付款订单付款或退货
    '''
    states = (('pay', '已付款'), ('ret', '已退货'))
    tid = forms.IntegerField(label='订单编号')
    paid = forms.CharField(label='付款状态', widget=forms.widgets.Select(choices=states))


class PubSearchForm(forms.Form):
    name = forms.CharField(label='出版社名称', max_length=30, required=False)


class PubUpdateForm(forms.Form):
    name = forms.CharField(label='出版社名称', max_length=30)


class AuthorSearchForm(forms.Form):
    name = forms.CharField(label='作者姓名', max_length=50, required=False)


class AuthorUpdateForm(forms.Form):
    name = forms.CharField(label='作者姓名', max_length=50)


class CatSearchForm(forms.Form):
    name = forms.CharField(label='类型名称', max_length=10, required=False)


class CatUpdateForm(forms.Form):
    name = forms.CharField(label='类型名称', max_length=10)

bookstore/templates/bookstore/add_book.html
{% extends "base.html" %}

{% block content %}

{% if state == 'success' %}
    <div class="well">
        <h2>交易成功</h2>
    </div>
{% endif %}
<form method="POST" role="form" class="form-inline">
    {% csrf_token %}
    <h1>补充库存</h1>
    <p>交易对象：</p>
    <p><strong>书名：</strong> {{ book.name }}</p>
    <p><strong>作者：</strong> {{ book.get_author }}</p>
    <p><strong>ISBN:</strong> {{ book.ISBN }}</p>
    <p><strong>出版社:</strong> {{ book.publisher }}</p>
    <p><strong>库存量:</strong> {{ book.inventory }}</p>
    <p><strong>零售价:</strong> {{ book.price }}</p>

    <div class="form-group">
      <label for="id_amount">数量：</label>
      <input type="text" class="form-control" id="id_amount" required name="amount" placeholder="请输入一个正整数">
    </div>

    <div class="form-group">*
      <label for="id_cost">进价：</label>
      <input type="text" class="form-control" id="id_cost" required name="cost" placeholder="请输入0.01-999.99的至多两位小数">
    </div>

    <div class="form-group">
      <button class="btn btn-default" type="submit">提交订单</button>
      <button class="btn btn-default" type="reset">重置</button>
    </div>
</form>
<p>若点击“提交订单”后仍返回此页面，则表示交易失败。请确保填写格式符合上述要求！</p>

{% if messages %}
<script>
    {% for msg in messages %}
        alert('{{ msg.message }}');
    {% endfor %}
</script>
{% endif %}


{% endblock %}

bookstore/templates/bookstore/author_books.html
{% extends 'base.html' %}

{% block content %}
  <div style="margin-left:20px;margin-top:20px">
    <h2>{{ author.name }}</h2>

    <a class="btn btn-default" href="{% url 'author_update' author.id %}" role="button">编辑信息</a>

    <h3>作品列表</h3>
    <table class="table table-hover">
      <thead>
        <tr>
            <th>图书编号</th>
            <th>书名</th>
            <th>出版社</th>
            <th>作者</th>
            <th>ISBN</th>
            <th>类型</th>
        </tr>
      </thead>
      <tbody>
        {% for book in author_books %}

          <tr>
            <td>{{ book.id }}</td>
            <td><a href="{{ book.get_absolute_url }}">{{ book.name }}</a></td>
            <td>{{ book.publisher }}</td>
            <td>{{ book.ISBN }}</td>
            <td>{{ book.get_author }}</td>
            <td>{{ book.get_category }}</td>
          </tr>
        {% empty %}
          <li>没有了，没有此人的著作了！</li>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

bookstore/templates/bookstore/author_list.html
{% extends "base.html" %}

{% block content %}

    <form method="POST" role="form" class="form-horizontal">
        {% csrf_token %}
        <h2 class="form-signin-heading text-center">检索作者</h2>

        <div class="form-group">
            <label for="id_name" class="col-md-3 control-label">作者姓名：</label>
            <div class="col-md-9">
                <input type="text" class="form-control" name="name" id="id_name">
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-4 col-md-offset-4">
                <button class="btn btn btn-primary btn-block" type="submit">搜索</button>
            </div>
        </div>
    </form>
    <p>若点击“搜索”后仍返回此页面，则表示检索失败。请确保填写格式符合上述要求！</p>

    {% if messages %}
    <script>
        {% for msg in messages %}
            alert('{{ msg.message }}');
        {% endfor %}
    </script>
    {% endif %}

    <h1>作者一览表</h1>
    {% if all_authors %}
    <ul>

      {% for author in all_authors %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.name }}</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>没有了，没有作者了！</p>
    {% endif %}


{% endblock %}

bookstore/templates/bookstore/author_update.html
{% extends 'base.html' %}

{% block content %}
    <div class="body">
    <h1>编辑用户信息</h1>
        <h2 class="title-style">可以编辑以下信息</h2>
        <div class="form-wrapper">
            <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="fieldWrapper">
                    {{ field.errors }}
                    {{ field.label_tag }}{{ field }}
                    {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
            {% endfor %}

            <div class="button-wrapper submit">
                <input type="submit" value="提交">
                <input type="reset" value="重置">
            </div>
            </form>
        </div>

    {% if messages %}
    <script>
        {% for msg in messages %}
            alert('{{ msg.message }}');
        {% endfor %}
    </script>
    {% endif %}

    <li><a href="{% url 'author_books' author.id %}">取消编辑</a></li>

    </div>


{% endblock %}

bookstore/templates/bookstore/cat_update.html
{% extends 'base.html' %}

{% block content %}
    <div class="body">
    <h1>编辑类型信息</h1>
        <h2 class="title-style">可以编辑以下信息</h2>
        <div class="form-wrapper">
            <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="fieldWrapper">
                    {{ field.errors }}
                    {{ field.label_tag }}{{ field }}
                    {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
            {% endfor %}

            <div class="button-wrapper submit">
                <input type="submit" value="提交">
                <input type="reset" value="重置">
            </div>
            </form>
        </div>

    {% if messages %}
    <script>
        {% for msg in messages %}
            alert('{{ msg.message }}');
        {% endfor %}
    </script>
    {% endif %}

    <li><a href="{% url 'cat_books' cat.id %}">取消编辑</a></li>

    </div>


{% endblock %}

bookstore/templates/bookstore/edit_book.html
{% extends 'base.html' %}

{% block content %}
    <div class="body">
    <h1>编辑图书信息</h1>
        <h2>可以编辑以下信息</h2>
        <p> 多位作者间用中文逗号隔开</p>
        <div class="form-wrapper">
            <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="fieldWrapper">
                    {{ field.errors }}
                    {{ field.label_tag }}{{ field }}
                    {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
            {% endfor %}
            <div class="form-group">
                <div class="col-md-4 col-md-offset-4">
                    <button class="btn btn btn-primary btn-block" type="submit">提交</button>
                    <button class="btn btn btn-primary btn-block" type="reset">重置</button>
                </div>
            </div>
            </form>
        </div>
    <a href="{% url 'related_transaction' book.id %}">取消编辑</a>
    </div>

    {% if messages %}
    <script>
        {% for msg in messages %}
            alert('{{ msg.message }}');
        {% endfor %}
    </script>
    {% endif %}

{% endblock %}

bookstore/templates/bookstore/payment.html
{% extends "base.html" %}

{% block content %}

    <form method="POST" role="form" class="form-inline">
        {% csrf_token %}

        <div class="form-group">
            <label for="id_tid" class="col-md-3 control-label">交易单号：</label>
            <input type="text" class="form-control" name="tid" id="id_tid">
        </div>

        <label class="radio-inline" for="pay">
          <input type="radio" name="paid" id="icontactChoice1" value="已付款" checked> 已付款
        </label>
        <label class="radio-inline" for="ret">
          <input type="radio" name="paid" id="icontactChoice2" value="已退货" checked> 已退货
        </label>

        <div class="form-group">
                <button class="btn btn-default" type="submit">执行</button>
                <button class="btn btn-default" type="reset">重置</button>
        </div>
    </form>
    <p>若点击“执行”后仍返回此页面，则表示检索失败。请确保填写格式符合上述要求！</p>

    {% if messages %}
    <script>
        {% for msg in messages %}
            alert('{{ msg.message }}');
        {% endfor %}
    </script>
    {% endif %}

    <h1>未付款交易记录一览表</h1>
    {% if up_trans %}
    <ul>

      {% for tran in up_trans %}
      <li>
        <p>交易单号：{{ tran.id }}</p>
        <p>商品信息：{{ tran.book }}</p>
        <p>交易时间：{{ tran.time|date:'Y 年 M d 日 H:i' }}</p>
        <p>进货出货：{{ tran.in_out }}</p>
        <p>交易数量：(本){{ tran.amount }}</p>
        <p>成交价格：{{ tran.cost }}</p>
        <p>付款状态：{{ tran.paid }}</p>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>没有了，没有未付款的订单了！</p>
    {% endif %}


{% endblock %}

bookstore/templates/bookstore/profile.html
{% extends 'base.html' %}

{% block content %}
    <div class="body">
        <h2 class="title-style">用户信息</h2>
        <ul class="b1">
        <li>用户名：{{ admin.user.username }}</li>
        <li>邮箱：{{ admin.user.email }}</li>
        <li>姓名：{{ admin.name }}</li>
        <li>年龄：{{ admin.age }}</li>
        <li>性别：{{ admin.gender }}</li>
        <li>住址：{{ admin.address }}</li>
        </ul>
        <p>联系方式：</p>
        <ul>
            {% for phone in phones %}
            <li>
                {{ phone.number }}
            </li>
            {% empty %}
            <li>
                没有了，没有此人的电话号码了！
            </li>
            {% endfor %}
        </ul>

        <a class="btn btn-default" href="{% url 'profile_update' user.id %}" role="button">编辑信息</a>

        <h2>负责订单</h2>

    <table class="table table-hover">
      <thead>
        <tr>
            <th>交易单号</th>
            <th>商品信息</th>
            <th>交易时间</th>
            <th>货物流向</th>
            <th>交易数量</th>
            <th>成交价格</th>
            <th>付款状态</th>
            <th>负责人</th>
        </tr>
      </thead>
      <tbody>
        {% for trans in res_trans %}
          <tr>
            <td>{{ trans.id }}</td>
            <td>{{ trans.book }}</td>
            <td>{{ trans.time|date }}</td>
            <td>{{ trans.in_out }}</td>
            <td>{{ trans.amount }}</td>
            <td>{{ trans.cost }}</td>
            <td>{{ trans.paid }}</td>
            <td>{{ trans.ruler }}</td>
          </tr>
        {% empty %}
          <li>暂无交易记录！</li>
        {% endfor %}
      </tbody>
    </table>
    </div>



{% endblock %}

bookstore/templates/bookstore/pub_books.html
{% extends 'base.html' %}
{% block title %}<h1 class="my-con1">出版社信息</h1>{% endblock %}

{% block content %}
    <div class="body">
        <h2>出版社基本信息</h2>
        <ul class="b1">
        <li>出版社名称：{{ publisher.name }}</li>
        </ul>

        <a href="{% url 'pub_update' publisher.id %}" class="m1">编辑信息</a>

        <h2>出版图书</h2>
        <ul class="b1">
        {% for book in published_books %}
        <li>
          <a href="{{ book.get_absolute_url }}">{{ book.name }}</a> ({{book.get_author}})
        </li>
        {% empty %}
        <li>
            没有了，没有这家出版的图书了！
        </li>
        {% endfor %}
        </ul>
    </div>



{% endblock %}

bookstore/templates/bookstore/publisher_list.html
{% extends "base.html" %}

{% block content %}

    <form method="POST" role="form" class="form-horizontal">
        {% csrf_token %}
        <h2 class="form-signin-heading text-center">检索抽象圣经出版社</h2>

        <div class="form-group">
            <label for="id_name" class="col-md-3 control-label">出版社名称：</label>
            <div class="col-md-9">
                <input type="text" class="form-control" id="id_name" name="name">
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-4 col-md-offset-4">
                <button class="btn btn btn-primary btn-block" type="submit">搜索</button>
            </div>
        </div>
    </form>
    <p>若点击“搜索”后仍返回此页面，则表示检索失败。请确保填写格式符合上述要求！</p>

    <h2>抽象圣经出版社一览表</h2>

    {% if pubs %}
    <ul>

      {% for pub in pubs %}
      <li>
        <p><a href="{{ pub.get_absolute_url }}">{{ pub.name }}</a></p>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>居然没人出版抽象圣经？在？道个歉？</p>
    {% endif %}       
{% endblock %}

bookstore/templates/bookstore/search.html
{% extends "base.html" %}

{% block content %}
    <h1>抽象圣经检索结果</h1>

    {% if selected_books %}
    <ul>

      {% for book in selected_books %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.name }}</a> ({{book.get_author}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>没有了，没有抽象圣经了！</p>
    {% endif %}
{% endblock %}

bookstore/templates/bookstore/transaction_list.html
{% extends "base.html" %}

{% block content %}

    <form method="POST" role="form" class="form-inline">
        {% csrf_token %}
        <h2>检索抽象圣经交易记录</h2>
        <p><strong>注意：</strong>起始时间和结束时间都是必填项；日期视作当天00:00</p>

        <div class="form-group">
            <label for="id_start_time">起始时间：</label>
            <input type="date" class="form-control" id="id_start_time" name="start_time">
        </div>

        <div class="form-group">
            <label for="id_end_time">结束时间：</label>
            <input type="date" class="form-control" id="id_end_time" name="end_time">
        </div>

        <label class="radio-inline" for="in">
          <input type="radio" name="stat" id="icontactChoice1" value="进货" checked> 进货
        </label>
        <label class="radio-inline" for="out">
          <input type="radio" name="stat" id="icontactChoice2" value="出货" checked> 出货
        </label>

        <div class="form-group">
            <div class="col-md-4 col-md-offset-4">
                <button class="btn btn-default" type="submit">搜索</button>
                <button class="btn btn-default" type="reset">重置</button>
            </div>
        </div>
    </form>
    <p>若点击“搜索”后仍返回此页面，则表示检索失败。请确保填写格式符合上述要求！</p>


    <h2 class="form-signin-heading text-center">交易记录列表</h2>
    <a class="btn btn-default" href="{% url 'payment' %}" role="button">更改进货订单状态</a>
    {% if transactions %}

    <table class="table table-hover">
      <thead>
        <tr>
            <th>交易单号</th>
            <th>商品信息</th>
            <th>交易时间</th>
            <th>货物流向</th>
            <th>交易数量</th>
            <th>成交价格</th>
            <th>付款状态</th>
            <th>负责人</th>
        </tr>
      </thead>
      <tbody>
        {% for trans in transactions %}
          <tr>
            <td>{{ trans.id }}</td>
            <td>{{ trans.book }}</td>
            <td>{{ trans.time|date }}</td>
            <td>{{ trans.in_out }}</td>
            <td>{{ trans.amount }}</td>
            <td>{{ trans.cost }}</td>
            <td>{{ trans.paid }}</td>
            <td>{{ trans.ruler }}</td>
          </tr>
        {% empty %}
          <li>暂无交易记录！</li>
        {% endfor %}
      </tbody>
    </table>

    {% else %}
      <p>居然没人买抽象圣经？在？道个歉？</p>
    {% endif %}
{% endblock %}